version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  application:
    build:
      context: "./"
    
    environment:
      - MONGODB_URI=mongodb+srv://usermarket:ycLSafffXF7bAwLU@cluster0.baaj2.mongodb.net/Marketplace
      - DEBUG=app:*
      - NODE_ENV=development
    container_name: application
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

      
volumes:
  mongo-data:   
  redis-data: